name: Compile Latex and deploy

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
    
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    container: thomasweise/docker-texlive-full
    env:
      DEBIAN_FRONTEND: noninteractive
        
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Install things
      run: |
        apt-get update
        apt-get install -y python3 zip tzdata 
        #texlive texlive-latex-recommended texlive-latex-extra texlive-science texlive-pictures
        ln -fs /usr/share/zoneinfo/Europe/Oslo /etc/localtime
        dpkg-reconfigure --frontend noninteractive tzdata

    - name: Compile latex
      run: python3 build.py

    - name: ls publish folder
      run: ls -a publish/
      
    - uses: jsmrcaga/action-netlify-deploy@v1
      with:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_ACCESS_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        NETLIFY_DEPLOY_TO_PROD: true
        build_directory: publish
